/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package segurtasun;

import junit.framework.TestCase;
import segurtasun.App;

public class AppTest extends TestCase {
    App app = null;

    public void setUp() throws Exception {
        super.setUp();
        app = new App();
    }

    public void tearDown() throws Exception {
    }

    public void testZifratu() {
        assertEquals("BP MZTVB MBWWZWBJ ZGVB", app.zifratu("EZ GAUDE GERRAREN ALDE"));
    }
    public void testDeszifratu() {

        assertEquals("EZ GAUDE GERRAREN ALDE",
                app.deszifratu(
                        app.zifratu("EZ GAUDE GERRAREN ALDE")));

    }
}

