/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package segurtasun;

public class App {
    public String zifratu(String pMezua,String pGakoa){
        int i;
        int lag;
        pMezua=pMezua.toUpperCase();
        pGakoa=pGakoa.toUpperCase();
        char kar;
        String emaitza="";
        for (i=0;i<pMezua.length();i++){
            kar =pMezua.charAt(i);
            lag= kar;
            lag=lag-65;
            emaitza+=pGakoa.charAt(lag);
        }
        return emaitza;
    }
    public String deszifratu(String pMezua,String pGakoa){
        int i;
        int t;
        boolean irten;
        pMezua=pMezua.toUpperCase();
        pGakoa=pGakoa.toUpperCase();
        char kar;
        String emaitza="";
        for (i=0;i<pMezua.length();i++){
            kar=pMezua.charAt(i);
            t=0;
            irten=false;
            while (t<pGakoa.length() && !irten){
            if (kar==pGakoa.charAt(t)){
                irten=true;
            }
            t++;
            }
            t=t+64;
            emaitza+= (char) t;
        }
        return emaitza;
    }
    public static void main(String[] args) {
        System.out.println(new App().zifratu("hola","abcdefghijklmnopqrstuvwxyz"));
        System.out.println(new App().zifratu("zzzz","abcdefghijklmnopqrstuvwxyz"));
        System.out.println(new App().zifratu("hola","zabcdefghijklmnopqrstuvwxy"));
        System.out.println(new App().deszifratu("GNKZ","zabcdefghijklmnopqrstuvwxy"));
       // System.out.println("asssssssssssssfssfwa");
    }
}
