/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package segurtasun;

public class OrdezkatzeHiztegia {
    private String gakoa="ZXCVBNMASDFGHJKLQWERTYUIOP";

    public String zifratu(String pMezua){
        int i;
        int lag;
        pMezua=pMezua.toUpperCase();
        this.gakoa=this.gakoa.toUpperCase();
        char kar;
        String emaitza="";
        for (i=0;i<pMezua.length();i++){
            kar =pMezua.charAt(i);
            if(kar==' '){
                emaitza+=' ';
            }
            else{
            lag= (int) kar;
            lag=lag-65;
            emaitza+=this.gakoa.charAt(lag);
            }
        }
        return emaitza;
    }
    public String deszifratu(String pMezua){
        int i;
        int t;
        boolean irten;
        pMezua=pMezua.toUpperCase();
        this.gakoa=this.gakoa.toUpperCase();
        char kar;
        String emaitza="";
        for (i=0;i<pMezua.length();i++){
            kar=pMezua.charAt(i);
            if(kar==' '){
                emaitza+=' ';
            }
            else {
                t = 0;
                irten = false;
                while (t < this.gakoa.length() && !irten) {
                    if (kar == this.gakoa.charAt(t)) {
                        irten = true;
                    }
                    t++;
                }
                t = t + 64;
                emaitza += (char) t;
            }
        }
        return emaitza;
    }
    public static void main(String[] args) {
        System.out.println(new OrdezkatzeHiztegia().zifratu("hola"));
        System.out.println(new OrdezkatzeHiztegia().zifratu("zzzz"));
        System.out.println(new OrdezkatzeHiztegia().zifratu("ho la"));
        System.out.println(new OrdezkatzeHiztegia().deszifratu("GNKZ"));
       // System.out.println("asssssssssssssfssfwa");
    }
}
